version: "3.8"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: radicalization_bot
    container_name: radicalization_bot
    restart: unless-stopped
    ports:
      - 8000:8000   # Backend API
      - 8501:8501   # Frontend UI
    volumes:
      - ./logs:/app/logs
    environment:
      - SOME_ENV_VAR=value
