
services:
  backend:
    build:
      context: .
    command: python -m uvicorn api:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build:
      context: .
    command: python -m streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    depends_on:
      - backend
    env_file:
      - .env
