services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: radicalization_bot
    #container_name: radicalization_bot
    restart: unless-stopped
    ports:
      - "${API_PORT:-8001}:8000"   # FastAPI
      - "${UI_PORT:-8502}:8501"    # Streamlit
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    environment:
      - CHAT_AI_ACCESS_KEY=${CHAT_AI_ACCESS_KEY}
      - API_BASE_URL=${API_BASE_URL:-http://localhost}
      - API_PORT=${API_PORT:-8001}
      - UI_PORT=${UI_PORT:-8502}
